language: objective-c
osx_image: xcode7.2
env:
  global: 
    - PROJECT_NAME=swift-express
before_install:
  - brew update
  - brew unlink carthage
  - brew install carthage
  - brew link carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --platform osx
script:
  - xcodebuild test -project $PROJECT_NAME.xcodeproj -scheme $PROJECT_NAME
notifications:
  email: false

